### PR TITLE
FEATURE: add comment_date_gmt for additional signal

### PR DESCRIPTION
**Pull request by SamSaffron**
Akismet can use the date of the comment as extra signal for spam checking

Add it.

### CODE REVIEW

**Review by stephdau — COMMENTED** [review]
I won't approve it because I'm not setup to test properly, but wanted to mention that this looks great to me, and will add a very useful signal for Akismet to leverage. Thanks, Sam. 🙂

**Comment by SamSaffron** [comment]
Thanks heaps @stephdau we will get this merged shortly. You should see the new signal come in via meta.discourse.org within a day. It will be cycled throughout our hosting in the next few weeks

**Comment by stephdau** [comment]
Fantastic!

**Review by nattsw — APPROVED** [review]

**Comment by stephdau** [comment]
Confirming that we're starting to see `created_date`/`comment_date_gmt` coming in on the Akismet side (from meta.discourse.org and others), and things are looking good.

**Pull request merged**
